SHOWS_MAP = {
    'abstract': 'Abstract - The Art Of Design',
    'abstract the art of design': 'Abstract - The Art Of Design',
    'american dad!': 'American Dad',
    'avatar': 'Avatar - The Last Airbender',
    'avatar the last airbender': 'Avatar - The Last Airbender',
    'brooklyn nine nine': 'Brooklyn Nine-Nine',
    'buffy': 'Buffy - The Vampire Slayer',
    'buffy the vampire slayer': 'Buffy - The Vampire Slayer',
    'cosmos': 'Cosmos - A Spacetime Odyssey',
    'cosmos a spacetime odyssey': 'Cosmos - A Spacetime Odyssey',
    'dirk gentlys holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'flashforward': 'FlashForward',
    'the fresh prince of bel air': 'The Fresh Prince Of Bel-Air',
    'gilmore girls a year in the life': 'Gilmore Girls - A Year In The Life',
    'greys anatomy': 'Grey\'s Anatomy',
    'its always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'james clavells shogun': 'Shogun',
    'the jinx': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the jinx the life and deaths of robert durst': 'The Jinx - The Life And Deaths Of Robert Durst',
    'married. with children': 'Married With Children',
    'married... with children': 'Married With Children',
    'agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'daredevil': 'Marvel\'s Daredevil',
    'marvels daredevil': 'Marvel\'s Daredevil',
    'iron fist': 'Marvel\'s Iron Fist',
    'marvels iron fist': 'Marvel\'s Iron Fist',
    'jessica jones': 'Marvel\'s Jessica Jones',
    'marvels jessica jones': 'Marvel\'s Jessica Jones',
    'luke cage': 'Marvel\'s Luke Cage',
    'marvels luke cage': 'Marvel\'s Luke Cage',
    'mortal kombat legacy': 'Mortal Kombat - Legacy',
    'mr robot': 'Mr. Robot',
    'planet earth ii': 'Planet Earth II',
    'six': 'SIX',
    'spiderman': 'Spider-Man',
    'spider man': 'Spider-Man',
    'stargate atlantis': 'Stargate - Atlantis',
    'stargate': 'Stargate - SG-1',
    'stargate sg-1': 'Stargate - SG-1',
    'stargate sg 1': 'Stargate - SG-1',
    'that 70s show': 'That 70\'s Show',
    'this is': 'This Is Us',
    'vice': 'VICE',
    'welcome to': 'Welcome To Sweden',
    'the x files': 'The X-Files',
    'x men': 'X-Men',
    'x men the animated series': 'X-Men'
}
