SHOWS_MAP = {
    '24 legacy': '24 - Legacy',
    'abstract': 'Abstract - The Art Of Design',
    'abstract the art of design': 'Abstract - The Art Of Design',
    'american dad!': 'American Dad',
    'the americans': 'The Americans (2013)',
    'archer': 'Archer (2009)',
    'avatar': 'Avatar - The Last Airbender',
    'avatar the last airbender': 'Avatar - The Last Airbender',
    'battlestar galactica': 'Battlestar Galactica (2003)',
    'the blacklist redemption': 'The Blacklist - Redemption',
    'the bridge': 'The Bridge (2011)',
    'brooklyn nine nine': 'Brooklyn Nine-Nine',
    'buffy': 'Buffy - The Vampire Slayer',
    'buffy the vampire slayer': 'Buffy - The Vampire Slayer',
    'cosmos': 'Cosmos - A Spacetime Odyssey',
    'cosmos a spacetime odyssey': 'Cosmos - A Spacetime Odyssey',
    'dcs legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'legends of tomorrow': 'DC\'s Legends Of Tomorrow',
    'dirk gentlys holistic detective agency': 'Dirk Gently\'s Holistic Detective Agency',
    'doctor who': 'Doctor Who (2005)',
    'dragon ball gt': 'Dragon Ball GT',
    'empire': 'Empire (2015)',
    'the flash': 'The Flash (2014)',
    'flashforward': 'FlashForward',
    'the fresh prince of bel air': 'The Fresh Prince Of Bel-Air',
    'fullmetal alchemist brotherhood': 'Fullmetal Alchemist - Brotherhood',
    'gilmore girls a year in the life': 'Gilmore Girls - A Year In The Life',
    'the grand tour': 'The Grand Tour (2016)',
    'greys anatomy': 'Grey\'s Anatomy',
    'house of cards': 'House Of Cards (US)',
    'hunter x hunter': 'Hunter X Hunter (2011)',
    'the it crowd': 'The IT Crowd',
    'its always sunny in philadelphia': 'It\'s Always Sunny In Philadelphia',
    'james clavells shogun': 'James Clavell\'s Shogun',
    'shogun': 'James Clavell\'s Shogun',
    'jericho': 'Jericho (2006)',
    'the jinx': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the jinx the life and deaths of robert durst': 'The Jinx - The Life And Deaths Of Robert Durst',
    'the killing': 'The Killing (2011)',
    'life': 'Life (2009)',
    'lois & clark': 'Lois & Clark - The New Adventures Of Superman',
    'lois & clark the new adventures of superman': 'Lois & Clark - The New Adventures Of Superman',
    'lois and clark': 'Lois & Clark - The New Adventures Of Superman',
    'lois and clark the new adventures of superman': 'Lois & Clark - The New Adventures Of Superman',
    'louie': 'Louie (2010)',
    'the magicians': 'The Magicians (2016)',
    'marco polo': 'Marco Polo (2014)',
    'married. with children': 'Married With Children',
    'married... with children': 'Married With Children',
    'agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of shield': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'marvels agents of s.h.i.e.l.d.': 'Marvel\'s Agents Of S.H.I.E.L.D.',
    'daredevil': 'Marvel\'s Daredevil',
    'marvels daredevil': 'Marvel\'s Daredevil',
    'iron fist': 'Marvel\'s Iron Fist',
    'marvels iron fist': 'Marvel\'s Iron Fist',
    'jessica jones': 'Marvel\'s Jessica Jones',
    'marvels jessica jones': 'Marvel\'s Jessica Jones',
    'luke cage': 'Marvel\'s Luke Cage',
    'marvels luke cage': 'Marvel\'s Luke Cage',
    'mortal kombat legacy': 'Mortal Kombat - Legacy',
    'mr robot': 'Mr. Robot',
    'the oa': 'The OA',
    'the office': 'The Office (US)',
    'once upon a time': 'Once Upon A Time (2011)',
    'parasyte': 'Parasyte - The Maxim',
    'parasyte the maxim': 'Parasyte - The Maxim',
    'planet earth ii': 'Planet Earth II',
    'read or die': 'R.O.D - Read Or Die',
    'r.o.d read or die': 'R.O.D - Read Or Die',
    'roots': 'Roots (2016)',
    'scandal': 'Scandal (2012)',
    'second chance': 'Second Chance (2016)',
    'shameless': 'Shameless (US)',
    'six': 'SIX',
    'spiderman': 'Spider-Man (1994)',
    'spider man': 'Spider-Man (1994)',
    'spider-man': 'Spider-Man (1994)',
    'stargate atlantis': 'Stargate - Atlantis',
    'stargate': 'Stargate - SG-1',
    'stargate sg-1': 'Stargate - SG-1',
    'stargate sg 1': 'Stargate - SG-1',
    'taboo': 'Taboo (2017)',
    'that 70s show': 'That 70\'s Show',
    'this is': 'This Is Us',
    'vice': 'VICE',
    'welcome to': 'Welcome To Sweden (2014)',
    'welcome to sweden': 'Welcome To Sweden (2014)',
    'wrecked': 'Wrecked (2016)',
    'the x files': 'The X-Files',
    'x men': 'X-Men',
    'x men the animated series': 'X-Men'
}
